# Generated by Django 2.1.3 on 2018-12-05 17:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=200, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='noticias', verbose_name='Imagen')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Dirección WEB')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-created', 'titulo'],
            },
        ),
    ]
