# Generated by Django 2.1.3 on 2018-12-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
