# Generated by Django 2.1.3 on 2018-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poblaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poblacion',
            name='avatar',
            field=models.ImageField(upload_to='poblaciones', verbose_name='Imagen'),
        ),
    ]
