# Generated by Django 2.1.3 on 2018-12-06 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='asignaturas', verbose_name='Imagen')),
                ('nivel', models.CharField(choices=[('NI INICIACION', 'Nivel I'), ('NII STANDARD', 'Nivel II'), ('NII REFORZADO', 'Nivel II reforzado'), ('NII ACCESO', 'Nivel II Acceso'), ('NIII', 'Nivel III'), ('MANTENIMIENTO', 'Mantenimiento'), ('AGRUPACION', 'Sólo agrupación')], default='NI INICIACION', max_length=13)),
                ('curso', models.CharField(choices=[('1º', 'Primero'), ('2º', 'Segundo'), ('3º', 'Tercero'), ('4º', 'Cuarto'), ('5º', 'Quinto'), ('5º', 'Sexto'), ('NA', 'No Aplica')], default='1º', max_length=25)),
                ('sesionesSemanales', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Sesiones semanales')),
                ('duracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(90)], verbose_name='Duración de la sesión')),
                ('aforoMaximo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Aforo máximo')),
                ('aforoMinimo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Aforo mínimo')),
                ('edadMinima', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(99)], verbose_name='Edad mínima')),
                ('edadMaxima', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(99)], verbose_name='Edad máxima')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'asignatura',
                'verbose_name_plural': 'asignaturas',
                'ordering': ['nombre'],
            },
        ),
    ]
