# Generated by Django 2.1.3 on 2018-12-06 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poblaciones', '0002_auto_20181206_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Superficie')),
                ('aforo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aforo máximo')),
                ('imagen', models.ImageField(upload_to='aulas', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('poblacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poblaciones.Poblacion')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['poblacion', 'nombre', 'superficie', 'aforo'],
            },
        ),
    ]
