# Generated by Django 2.1.3 on 2018-12-07 10:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno_gestor',
            options={'ordering': ['esGestor', 'alumno', 'rol'], 'verbose_name': 'Gestor del Alumno', 'verbose_name_plural': 'Gestores del Alumno'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='Conocimientos musicales previos', null=True, verbose_name='Conocimientos musicales previos'),
        ),
    ]
