# Generated by Django 2.1.3 on 2018-12-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20181207_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='avatar',
            field=models.ImageField(upload_to='alumnos', verbose_name='Imagen'),
        ),
        migrations.AlterUniqueTogether(
            name='alumno',
            unique_together={('nombre', 'primerApellido', 'segundoApellido', 'fechaNacimiento')},
        ),
    ]
