# Generated by Django 2.1.3 on 2018-12-06 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poblaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Personas', verbose_name='Avatar')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('primerApellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundoApellido', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('dni', models.CharField(max_length=9, verbose_name='D.N.I.')),
                ('telefonoPrincipal', models.CharField(max_length=9, verbose_name='Teléfono principal')),
                ('telefonoSecundario', models.CharField(blank=True, max_length=9, verbose_name='Teléfono secundario')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección postal')),
                ('tipoPerfil', models.CharField(choices=[('DOC', 'Docente'), ('GES', 'Gestor'), ('ADM', 'Administrativo')], default='GES', max_length=3, verbose_name='Perfil de usuario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre', 'primerApellido', 'segundoApellido'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.Persona')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Dirección WEB')),
                ('jornada', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100, 0)], verbose_name='Jornada')),
                ('rolDirector', models.BooleanField(null=True, verbose_name='Director')),
                ('rolJefatura', models.BooleanField(null=True, verbose_name='Jefatura')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nombre', 'primerApellido', 'segundoApellido'],
            },
            bases=('registration.persona',),
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.Persona')),
                ('numeroCC', models.CharField(blank=True, max_length=20, verbose_name='Número CC')),
                ('iban', models.CharField(blank=True, max_length=4, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=11, verbose_name='SWIFT')),
                ('rentaBasica', models.BooleanField(null=True)),
                ('familiaNumerosa', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'ordering': ['nombre', 'primerApellido', 'segundoApellido'],
            },
            bases=('registration.persona',),
        ),
        migrations.AddField(
            model_name='persona',
            name='poblacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poblaciones.Poblacion', verbose_name='Población'),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
