# Generated by Django 2.1.3 on 2018-12-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='familiaNumerosa',
            field=models.BooleanField(null=True, verbose_name='Familia Numerosa'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='rentaBasica',
            field=models.BooleanField(null=True, verbose_name='Renta Básica'),
        ),
    ]
