# Generated by Django 2.1.3 on 2018-12-06 16:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('primerApellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundoApellido', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('fechaNacimiento', models.DateField()),
                ('avatar', models.ImageField(upload_to='poblaciones', verbose_name='Imagen')),
                ('genero', models.CharField(choices=[('M', 'Másculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('centroEstudios', models.CharField(blank=True, choices=[('PI', 'HERMANAS URIZ PI'), ('JL', 'JOAKIN LIZARRAGA')], default='PI', max_length=2, null=True, verbose_name='Centro escolar')),
                ('activo', models.BooleanField(default=False, null=True, verbose_name='Activo')),
                ('empadronado', models.BooleanField(null=True, verbose_name='Empadronado en el valle de Egüés')),
                ('autorizaImagen', models.BooleanField(null=True, verbose_name='Autoriza uso imágen')),
                ('fichaMedica', models.BooleanField(null=True, verbose_name='Entrega ficha médica')),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Conocimientos musicales previos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre', 'primerApellido', 'segundoApellido'],
            },
        ),
        migrations.CreateModel(
            name='Alumno_Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol del Gestor respecto del Alumno')),
                ('esGestor', models.BooleanField(null=True, verbose_name='Gestiona trámites del alumno')),
                ('esPagador', models.BooleanField(null=True, verbose_name='Paga recibos del alumno')),
                ('recibeNotificaciones', models.BooleanField(null=True, verbose_name='Recibe las notificaciones relativas al alumno')),
                ('domicilioHabitual', models.BooleanField(null=True, verbose_name='Su domicilio es el habitual del alumno')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Gestor')),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'ordering': ['esGestor', 'alumno', 'rol'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='gestor',
            field=models.ManyToManyField(through='alumnos.Alumno_Gestor', to='registration.Gestor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.Docente'),
        ),
    ]
